### ISSUE TITLE
Find false errors in docstring

### ISSUE THREAD

**Issue by nbonnotte** [haypo/sixer#8]
```py
def unicode_foo():
    """
    Returns "foo" as a str in python3 and as a
    unicode in python2
    """
    return six.text_type("foo")
```
After applying `six --write unicode` on the file, my script looks like
```py
def unicode_foo():
    """
    Returns "foo" as a str in python3 and as a
    six.text_type in python2
    """
    return six.text_type("foo")
```
I'm using `sixer==1.6.1`

**Comment by vstinner** [comment]
sixer uses regex and isn't safe. As you noticed, it also modify docstrings, especially for the "unicode" operation. You can exclude this operation, or revert manually changes. You may try other tools: https://github.com/vstinner/sixer/#resources-to-port-code-to-python-3

I don't see how to fix the unicode operation since it only matchs the "unicode" string...
